name: Build Mold

on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Clone mold repository
        uses: actions/checkout@v2
        with:
          repository: rui314/mold
          submodules: recursive
        
      - name: Install LLVM 11
        shell: bash
        run: |
          sudo apt-get install clang-11
          sudo apt-get install libstdc++6
          sudo ln -sf clang-11 /usr/bin/clang
          sudo ln -sf clang++-11 /usr/bin/clang++
          
      - name: Build submodules
        run: make submodules
        shell: bash
        
      - name: Build
        run: make CC=gcc-10 CXX=g++-10 -j2
        shell: bash
        
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: mold
          path: mold
      
